version: "3"
volumes:
  notebook-data:
    driver: local

services:
  notebook:
    build: .
    ports:
      - 8888:8888
    volumes:
      - notebook-data:/home/jovyan/work:rw
      - ../bayeslite:/home/jovyan/bayeslite:rw
    #command: start.sh ipython
